server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 1MB      # Максимальный размер одного файла
      max-request-size: 10MB
    session:
      timeout: 30m

spring:
  application:
    name: cloud-storage-1
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml

storage:
  bucket-name: cloud-storage-files
  minio:
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin


logging:
  level:
    root: WARN  # Изменил с INFO на WARN
    org.example.cloudstorage1: INFO  # Только твои логи
    org.springframework.web: ERROR  # Минимум от Spring Web
    org.springframework.security: WARN
    org.hibernate: ERROR  # Полностью скрываем Hibernate
    org.hibernate.SQL: ERROR  # Скрываем SQL
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR  # Скрываем параметры
    liquibase: WARN  # Минимизируем Liquibase
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  file:
    name: logs/application.log
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

