spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cloud_storage
    username: user
    password: password

storage:
  minio:
    endpoint: http://minio:9000
    access-key: minioadmin
    secret-key: minioadmin